import{GlowBluetooth}from'./bluetooth.js';const bt=new GlowBluetooth(),$=s=>document.querySelector(s),N=72,state={effect:'Solid',color:'#00D9FF',brightness:80,speed:50,sensitivity:70,reaction:50,music:true,musicMode:'beat',rainbow:false};
const effects=[['Solid','●'],['Rainbow','🌈'],['Pulse','💓'],['Breathing','🌬️'],['Strobe','⚡'],['Flash','✨'],['Fire','🔥'],['Ocean','🌊'],['Meteor','☄️'],['Sparkle','✦'],['Twinkle','✧'],['Chase','➜'],['Scanner','◀'],['Wave','〰'],['VU Meter','📊'],['Spectrum','🎚️'],['Music Beat','🥁'],['Bass Pulse','🔊'],['Party','🎉'],['Police','🚨'],['Aurora','🌌'],['Sunset','🌅'],['Lightning','⛈️'],['Random','🎲']];
const colors=['#FF0000','#FF3300','#FF6600','#FF9900','#FFCC00','#FFFF00','#CCFF00','#66FF00','#00FF00','#00FF66','#00FFCC','#00FFFF','#00CCFF','#0066FF','#3300FF','#6600FF','#9900FF','#CC00FF','#FF00FF','#FF00CC','#FF0099','#FF0066','#FFFFFF','#DDE7FF','#A8C7FF','#70A7FF','#4B72FF','#111111','#FFB3B3','#FFD6A3','#FFF2B3','#D4FFB3','#B3FFD8','#B3FFFF','#B3D8FF','#D0B3FF','#FFB3F4','#FFB3D1','#FF7F50','#00CED1','#7FFFD4','#ADFF2F','#DA70D6','#FF69B4','#FF1493','#8A2BE2','#4B0082'];
const presets=[['Cyan Pulse','#00D9FF','Pulse'],['Pink Party','#FF00A8','Party'],['Rainbow','#FFFFFF','Rainbow'],['Fire','#FF4500','Fire'],['Ocean','#00BFFF','Ocean'],['Aurora','#7CFFB2','Aurora'],['Police','#FFFFFF','Police'],['Strobe','#FFFFFF','Strobe'],['Sunset','#FF6A00','Wave'],['Disco','#FF00FF','Random'],['White','#FFFFFF','Solid'],['Deep Blue','#164BFF','Breathing'],['Green Laser','#66FF00','Scanner'],['Purple Wave','#9B4DFF','Wave'],['Warm','#FF8A35','Breathing'],['Music VU','#00FFFF','VU Meter']];
function send(){bt.send({cmd:'state',...state})}function leds(){let b=$('#leds');b.innerHTML='';for(let i=0;i<N;i++){let e=document.createElement('i');e.className='led';e.style.background=state.color;e.style.color=state.color;e.style.opacity=state.brightness/100;b.append(e)}}
function setColor(c){if(!/^#[0-9a-f]{6}$/i.test(c))return;state.color=c.toUpperCase();$('#color').value=state.color;$('#hex').value=state.color;leds();send()}
function effect(x){state.effect=x;state.rainbow=x==='Rainbow';document.querySelectorAll('.effect').forEach(b=>b.classList.toggle('active',b.dataset.e===x));leds();send()}
effects.forEach(([n,i])=>{let b=document.createElement('button');b.className='effect';b.dataset.e=n;b.textContent=i+' '+n;b.onclick=()=>effect(n);$('#effects').append(b)});
colors.forEach(c=>{let b=document.createElement('button');b.className='swatch';b.style.background=c;b.title=c;b.onclick=()=>setColor(c);$('#palette').append(b)});
presets.forEach(([n,c,e])=>{let b=document.createElement('button');b.className='preset';b.innerHTML=`<strong>${n}</strong><small>${e} · ${c}</small>`;b.onclick=()=>{setColor(c);effect(e)};$('#presets').append(b)});
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')});
$('#color').oninput=e=>setColor(e.target.value);$('#applyHex').onclick=()=>setColor($('#hex').value.trim());
[['brightness','brightnessOut'],['speed','speedOut'],['sensitivity','sensitivityOut'],['reaction','reactionOut']].forEach(([a,o])=>$('#'+a).oninput=e=>{state[a]=+e.target.value;$('#'+o).textContent=e.target.value+'%';leds();send()});
document.querySelectorAll('.music-mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.music-mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.musicMode=b.dataset.mode;send()});
$('#musicToggle').onclick=()=>{state.music=!state.music;$('#musicToggle').textContent=state.music?'🎵 Musik-Reaktion AN':'🔇 Musik-Reaktion AUS';send()};
$('#rainbowBtn').onclick=()=>effect('Rainbow');$('#randomBtn').onclick=()=>{effect(effects[Math.floor(Math.random()*effects.length)][0]);setColor(colors[Math.floor(Math.random()*colors.length)])};
$('#offBtn').onclick=()=>{$('#brightness').value=0;state.brightness=0;$('#brightnessOut').textContent='0%';leds();send()};$('#onBtn').onclick=()=>{$('#brightness').value=80;state.brightness=80;$('#brightnessOut').textContent='80%';leds();send()};
$('#testBtn').onclick=()=>{if(!bt.test){bt.enableTest();$('#testBtn').textContent='🧪 Testmodus: AN';$('#deviceName').textContent='SoundMix Glow TEST';$('#status').textContent='● Test verbunden';$('#status').className='status online'}else{bt.disableTest();$('#testBtn').textContent='🧪 Testmodus: AUS';$('#deviceName').textContent='Kein Gerät verbunden';$('#status').textContent='● Getrennt';$('#status').className='status offline'}};
$('#connectBtn').onclick=async()=>{try{let n=await bt.connect();$('#deviceName').textContent=n;$('#status').textContent='● Verbunden';$('#status').className='status online'}catch(e){alert(e.message)}};
$('#savePreset').onclick=()=>{let n=prompt('Preset-Name','Mein Preset');if(!n)return;let snap=JSON.stringify(state),b=document.createElement('button');b.className='preset';b.innerHTML=`<strong>${n}</strong><small>${state.effect} · ${state.color}</small>`;b.onclick=()=>{Object.assign(state,JSON.parse(snap));$('#color').value=state.color;$('#hex').value=state.color;$('#brightness').value=state.brightness;$('#speed').value=state.speed;leds();effect(state.effect);send()};$('#presets').prepend(b)};
let bars=[];for(let i=0;i<24;i++){let b=document.createElement('i');b.className='bar';$('#musicBars').append(b);bars.push(b)}function anim(){let t=Date.now()/1000;document.querySelectorAll('.led').forEach((e,i)=>{let x=(Math.sin(t*(1+state.speed/45)+i*.35)+1)/2;if(state.effect==='Strobe')x=Math.sin(t*12)>0?1:.03;if(['Pulse','Breathing','Bass Pulse'].includes(state.effect))x=.1+.9*(Math.sin(t*(1+state.speed/50))+1)/2;if(['Chase','Scanner','Meteor'].includes(state.effect))x=Math.max(.03,1-Math.abs((i-(t*(3+state.speed/20))%N))/7);if(['Sparkle','Twinkle'].includes(state.effect))x=Math.random()>.92?1:.1;e.style.opacity=Math.max(.02,x*state.brightness/100);if(state.rainbow){let h=(i*360/N+t*50)%360;e.style.background=`hsl(${h},100%,60%)`}});bars.forEach(b=>b.style.height=(5+Math.random()*48*(state.music?state.sensitivity/100:.1))+'px');requestAnimationFrame(anim)}leds();effect('Solid');anim();